// input: AppShell, TopBar, ActivityRail, and ProjectManagerPanel source
// output: Static regression for popover-only project management IA
// pos: Full-page ProjectHub is abandoned; rail popover is the manage surface

import { describe, expect, it } from 'bun:test'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const appShellSource = readFileSync(new URL('../AppShell.tsx', import.meta.url), 'utf8')
const topBarSource = readFileSync(new URL('../TopBar.tsx', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('../../../App.tsx', import.meta.url), 'utf8')
const activityRailPath = fileURLToPath(new URL('../ActivityRail.tsx', import.meta.url))
const activityRailSource = readFileSync(activityRailPath, 'utf8')
const projectSwitcherPath = fileURLToPath(new URL('../ProjectSwitcherPopover.tsx', import.meta.url))
const projectSwitcherSource = readFileSync(projectSwitcherPath, 'utf8')
const projectManagerPath = fileURLToPath(new URL('../ProjectManagerPanel.tsx', import.meta.url))
const projectManagerSource = readFileSync(projectManagerPath, 'utf8')

describe('project management entry', () => {
  it('keeps project management in the workspace header instead of a standalone rail icon', () => {
    expect(activityRailSource).toContain('data-tutorial="activity-project-hub"')
    expect(activityRailSource).toContain('aria-label="工作区导航"')
    expect(activityRailSource).toContain('aria-label="新建或导入项目"')
    expect(activityRailSource).not.toContain('aria-label="项目"')
    expect(topBarSource).not.toContain('onOpenProjectHub')
  })

  it('hosts create/import/remote/rename/remove inside the project manager panel', () => {
    expect(existsSync(projectManagerPath)).toBe(true)
    expect(projectManagerSource).toContain('data-testid="project-manager-panel"')
    expect(projectManagerSource).toContain('新建项目')
    expect(projectManagerSource).toContain('导入文件夹')
    expect(projectManagerSource).toContain('连接远端')
    expect(projectManagerSource).toContain('最近项目')
    expect(projectManagerSource).toContain('返回项目')
    expect(projectManagerSource).toContain('<ProjectActionButton')
    expect(projectManagerSource).not.toContain('ProjectActionCard')
    expect(projectManagerSource).toContain('重命名')
    expect(projectManagerSource).toContain('移除')
    expect(projectManagerSource).toContain('新窗口打开')
    expect(projectManagerSource).toContain("view === 'create'")
    expect(projectManagerSource).toContain('<AddWorkspaceStep_CreateNew')
    expect(projectManagerSource).toContain('<AddWorkspaceStep_OpenFolder')
    expect(projectManagerSource).toContain('<AddWorkspaceStep_ConnectRemote')
    expect(projectManagerSource).toContain('embedded')
    expect(projectManagerSource).not.toContain('管理全部项目')
    expect(projectSwitcherSource).toContain('<ProjectManagerPanel')
    expect(projectSwitcherSource).toContain('variant="dialog"')
    expect(projectSwitcherSource).toContain('<Dialog')
    expect(projectSwitcherSource).toContain('onWorkspaceCreated={onWorkspaceCreated}')
    expect(appSource).toContain('variant="standalone"')
    expect(appSource).toContain('{...projectManagerActions}')
    expect(appSource).toContain('onWorkspaceCreated:')
    expect(appSource).not.toMatch(/<ProjectHub[\s>]/)
  })

  it('wires project manager actions through the room AppShell rail', () => {
    expect(appShellSource).toContain('onWorkspaceCreated={onWorkspaceCreatedFromRail ?? onWorkspaceCreated}')
    expect(appShellSource).toContain('onRenameProject={onRenameProject}')
    expect(appShellSource).toContain('onRemoveProject={onRemoveProject}')
    expect(appShellSource).toContain('onOpenProjectInNewWindow={onOpenProjectInNewWindow}')
    expect(appShellSource).toContain('workspaces={workspaces}')
    expect(appShellSource).toContain('void onSelectWorkspace?.(workspaceId)')
    expect(activityRailSource).toContain('<ProjectSwitcherPopover')
    expect(activityRailSource).toContain('onWorkspaceCreated={onWorkspaceCreated}')
    expect(activityRailSource).not.toContain('onCreateProject')
    expect(activityRailSource).not.toContain('onManageProjects')
    expect(activityRailSource).not.toContain('退出到作品库')
  })

  it('keeps plugin navigation at the top of the single workspace sidebar', () => {
    expect(appShellSource).toContain('const showActivityRail = true')
    expect(appShellSource).toContain('<ActivityRail')
    expect(activityRailSource).toContain('label="最近对话"')
    expect(activityRailSource).toContain('label="项目"')
    expect(activityRailSource).toContain('RECENT_SESSION_LIMIT = 8')
    expect(activityRailSource).toContain('getAllSessions')
    expect(activityRailSource).toContain('onSelectSession')
    expect(activityRailSource).toContain('label="技能"')
    expect(activityRailSource).toContain('label="数据源"')
    expect(activityRailSource).toContain('label="搜索"')
    expect(activityRailSource).not.toContain('label="写作工作区"')
    expect(activityRailSource).not.toContain('dataTutorial="activity-writing"')
    expect(activityRailSource).toContain('aria-label="插件导航"')
    expect(activityRailSource).toContain('aria-label="个人菜单"')
    const skillsIndex = activityRailSource.indexOf('label="技能"')
    const sourcesIndex = activityRailSource.indexOf('label="数据源"')
    const searchIndex = activityRailSource.indexOf('label="搜索"')
    expect(skillsIndex).toBeLessThan(sourcesIndex)
    expect(sourcesIndex).toBeLessThan(searchIndex)
    expect(activityRailSource).not.toContain('{!isLibrary ? (')
    expect(appShellSource).toContain('onOpenSources={handleSourcesClick}')
    expect(appShellSource).toContain('onOpenSkills={handleSkillsClick}')
    expect(appShellSource).toContain('onOpenFreeConversations={onOpenFreeConversations}')
    expect(activityRailSource).not.toContain('dataTutorial="activity-free-conversations"')
  })

  it('keeps one profile item at the bottom and nests secondary actions inside it', () => {
    expect(activityRailSource).toContain('data-tutorial="activity-profile"')
    expect(activityRailSource).toContain('<DropdownMenuTrigger asChild>')
    expect(activityRailSource).toContain('账户')
    expect(activityRailSource).not.toContain('账户与积分')
    expect(activityRailSource).toContain('设置')
    expect(activityRailSource).toContain('新功能')
    expect(activityRailSource).toContain('帮助与反馈')
    expect(activityRailSource).not.toContain('aria-label="系统工具"')
    expect(activityRailSource).not.toContain('activity-check-updates')
    expect(appSource).toContain('profile={activityRailProfile}')
    expect(appShellSource).toContain('profile={profile}')
  })

  it('embeds the active project directory in the workspace rail instead of a second sidebar', () => {
    expect(appShellSource).toContain('const activityWorkspaceDirectory = showPrimarySidebar')
    expect(appShellSource).toContain('workspaceDirectory={activityWorkspaceDirectory}')
    expect(appShellSource).toContain('sidebarSlot={null}')
    expect(appShellSource).toContain('sidebarWidth={0}')
    expect(activityRailSource).toContain('data-testid="activity-project-directory"')
    expect(activityRailSource).toContain('className="min-w-0 overflow-hidden pl-3.5"')
    expect(activityRailSource).toContain('{workspaceDirectory}')
    expect(activityRailSource).toContain('projectWorkspaces.map((workspace) =>')
    expect(activityRailSource).toContain('workspace.id === activeWorkspaceId')
    expect(activityRailSource).not.toContain('.filter(workspace => !workspaceDirectory')
    expect(activityRailSource).not.toContain('className="-mx-2')
  })

  it('folds the whole project collection like recent conversations while preserving the native project root fold', () => {
    expect(activityRailSource).toContain('const [projectsExpanded, setProjectsExpanded]')
    expect(activityRailSource).toContain('storage.KEYS.activityProjectsExpanded')
    expect(activityRailSource).toContain('label="项目"')
    expect(activityRailSource).toContain('expanded={projectsExpanded}')
    expect(activityRailSource).toContain('{projectsExpanded ? (')
    expect(activityRailSource).toContain('data-testid="activity-sidebar-scroll"')
    expect(activityRailSource.match(/overflow-y-auto/g) ?? []).toHaveLength(1)
    expect(activityRailSource).toContain('overflow-x-hidden overflow-y-auto')
    expect(appShellSource).toContain('fitContent')
    expect(activityRailSource).not.toContain('workspaceDirectoryExpanded')
    expect(activityRailSource).not.toContain('h-[min(44vh,420px)]')
  })

  it('keeps global navigation usable from the project manager when an active project exists', () => {
    expect(appSource).toContain('const fallbackRuntimeWorkspaceId = useMemo(() =>')
    expect(appSource).toContain('workspace.id === FREE_CONVERSATION_WORKSPACE_ID')
    expect(appSource).toContain('const runtimeNavigationWorkspaceId = windowWorkspaceId')
    expect(appSource).toContain('?? activeProjectId')
    expect(appSource).toContain('?? fallbackRuntimeWorkspaceId')
    expect(appSource).toContain('const canOpenRuntimeNavigation = Boolean(runtimeNavigationWorkspaceId)')
    expect(appSource).toContain('const targetWorkspaceId = runtimeNavigationWorkspaceId')
    expect(appSource).toContain('onOpenSources: canOpenRuntimeNavigation')
    expect(appSource).toContain('onOpenSkills: canOpenRuntimeNavigation')
    expect(appSource).toContain('onOpenSearch: canOpenRuntimeNavigation ? handleOpenRuntimeSearch : undefined')
    expect(appSource).toContain('onOpenSettings: canOpenRuntimeNavigation')
    expect(appSource).toContain('onOpenWhatsNew: canOpenRuntimeNavigation ? handleOpenRuntimeWhatsNew : undefined')
    expect(appSource).toContain('openWhatsNewSignal={openWhatsNewSignal}')
    expect(appShellSource).toContain('if (openWhatsNewSignal > 0)')
  })

  it('opens a requested runtime route on the first click after activating a fallback project', () => {
    const pendingRouteEffect = appSource.slice(
      appSource.indexOf("if (appState !== 'ready' || !pendingReadyRoute) return"),
      appSource.indexOf('const openWorkspaceCreation')
    )

    expect(pendingRouteEffect).toContain('navigate(pendingReadyRoute)')
    expect(pendingRouteEffect).toContain('setPendingReadyRoute(null)')
    expect(pendingRouteEffect).not.toContain('requestAnimationFrame')
    expect(pendingRouteEffect).not.toContain('cancelAnimationFrame')
  })

  it('uses the workspace rail as the only session directory', () => {
    expect(appShellSource).toContain('const hideSessionListNavigator = showActivityRail && isSessionsNavigation(navState) && !isAutoCompact')
    expect(appShellSource).toContain('effectiveSidebarAndNavigatorHidden || hideSessionListNavigator ? 0 : navigatorPanelWidth')
    expect(appShellSource).toContain('!effectiveSidebarAndNavigatorHidden && !hideSessionListNavigator')
  })

  it('uses the title bar only for window chrome and current project context', () => {
    expect(topBarSource).toContain('data-testid="window-title-bar"')
    expect(topBarSource).not.toContain('<WorkspaceSwitcher')
    expect(topBarSource).not.toContain('onOpenProjectHub')
  })

  it('remounts the runtime shell when the active room changes', () => {
    expect(appSource).toContain("key={runtimeWorkspace?.id ?? 'no-runtime'}")
    expect(appSource).toContain('<WorkspaceSurface')
  })
})
