/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/auth-broker-worker/wrangler.toml --include-runtime=false --env-interface=AuthBrokerBindings apps/auth-broker-worker/worker-configuration.d.ts` (hash: eafea0a5b979735debb17cac8de9efc6)
interface __BaseEnv_AuthBrokerBindings {
	ACCESS_DB: D1Database;
	STORYFLOW_ACCESS_ENFORCEMENT: "legacy";
	STORYFLOW_CLIENT_SESSION_JWT_CURRENT_KEY_ID: "client-session-2026-07";
	STORYFLOW_GATEWAY_JWT_CURRENT_KEY_ID: "model-access-2026-07";
	STORYFLOW_SKILLS_MARKET_JWT_CURRENT_KEY_ID: "skills-market-2026-08";
	STORYFLOW_TOOL_GATEWAY_JWT_CURRENT_KEY_ID: "tool-access-2026-08";
	STORYFLOW_GATEWAY_JWT_AUDIENCE: "storyflow-model-gateway";
	STORYFLOW_GATEWAY_JWT_ISSUER: "storyflow-auth-broker";
	STORYFLOW_TOOL_GATEWAY_JWT_AUDIENCE: "storyflow-tool-gateway";
	STORYFLOW_TOOL_GATEWAY_JWT_ISSUER: "storyflow-auth-broker";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_AuthBrokerBindings {}
}
interface AuthBrokerBindings extends __BaseEnv_AuthBrokerBindings {}
