/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 46b474cb96c1e92fb2c689c186d99329)
interface __BaseEnv_Env {
	SEARCH_RATE_LIMITER: RateLimit;
	SCRAPE_RATE_LIMITER: RateLimit;
	STORYFLOW_TOOL_GATEWAY_JWT_CURRENT_KEY_ID: "tool-access-2026-08";
	STORYFLOW_TOOL_GATEWAY_JWT_CURRENT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEo1/2AdM3Ps5yC/jZrnchi4mjKzOi\n56lXbumb3y8je6fz9+6FcFrodnossdchTGyAUbEl3uABK1RhDKiiWIC0cQ==\n-----END PUBLIC KEY-----";
	STORYFLOW_TOOL_GATEWAY_JWT_AUDIENCE: "storyflow-tool-gateway";
	STORYFLOW_TOOL_GATEWAY_JWT_ISSUER: "storyflow-auth-broker";
	ANYSEARCH_UPSTREAM_URL: "https://api.anysearch.com/mcp";
	FIRECRAWL_UPSTREAM_URL: "https://api.firecrawl.dev/v2/scrape";
	ANYSEARCH_API_KEY: string;
	FIRECRAWL_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STORYFLOW_TOOL_GATEWAY_JWT_CURRENT_KEY_ID" | "STORYFLOW_TOOL_GATEWAY_JWT_CURRENT_PUBLIC_KEY" | "STORYFLOW_TOOL_GATEWAY_JWT_AUDIENCE" | "STORYFLOW_TOOL_GATEWAY_JWT_ISSUER" | "ANYSEARCH_UPSTREAM_URL" | "FIRECRAWL_UPSTREAM_URL" | "ANYSEARCH_API_KEY" | "FIRECRAWL_API_KEY">> {}
}
