// input: One LLM query plus initialized Pi auth, model registry, and runtime configuration
// output: Text generated by a disposable Pi AgentSession with provider-safe model fallback
// pos: Ephemeral completion lifecycle used by call_llm and product mini-completions

import {
  createAgentSession,
  SessionManager as PiSessionManager,
  DefaultResourceLoader,
  SettingsManager,
  getAgentDir,
} from '@earendil-works/pi-coding-agent';
import type {
  AgentSessionEvent,
  AuthStorage,
  CreateAgentSessionOptions,
  ModelRegistry,
} from '@earendil-works/pi-coding-agent';
import { getDefaultSummarizationModel } from '../../shared/src/config/models.ts';
import { THINKING_TO_PI } from '../../shared/src/agent/backend/pi/constants.ts';
import type { PiInitMessage } from '../../shared/src/agent/backend/pi/protocol.ts';
import {
  LLM_QUERY_TIMEOUT_MS,
  withTimeout,
  type LLMQueryRequest,
  type LLMQueryResult,
} from '../../shared/src/agent/llm-tool.ts';
import { createProviderHooks } from './provider-hooks.ts';
import { createSystemPromptOverride } from './system-prompt-override.ts';
import { resolvePiModel, isDeniedMiniModelId, isModelNotFoundError } from './model-resolution.ts';
import { pickProviderAppropriateMiniModel } from './pick-mini-model.ts';

interface EphemeralLlmQueryContext {
  config: PiInitMessage;
  cwd: string;
  authStorage: AuthStorage;
  modelRegistry: ModelRegistry;
  preferCustomEndpoint: boolean;
  debug: (message: string) => void;
}

export async function queryLlmWithEphemeralPiSession(
  request: LLMQueryRequest,
  context: EphemeralLlmQueryContext,
): Promise<LLMQueryResult> {
  const { config, authStorage, modelRegistry, preferCustomEndpoint, debug } = context;
  debug('[queryLlm] Starting');

  const piThinkingLevel = THINKING_TO_PI[
    config.thinkingLevel as keyof typeof THINKING_TO_PI
  ];
  let model = request.model ?? config.miniModel ?? getDefaultSummarizationModel();
  const piAuthProvider = config.piAuth?.provider;

  if (config.piAuth) {
    const authProvider = config.piAuth.provider;
    const bareModel = model.startsWith('pi/') ? model.slice(3) : model;
    const resolved = resolvePiModel(modelRegistry, bareModel, authProvider, preferCustomEndpoint);
    const resolvedProvider = (resolved as { provider?: string } | undefined)?.provider;
    const isCompatible = resolvedProvider === authProvider || resolvedProvider === 'custom-endpoint';
    if (!resolved || !isCompatible || isDeniedMiniModelId(model, piAuthProvider)) {
      const providerDefault = authProvider === 'anthropic'
        ? undefined
        : pickProviderAppropriateMiniModel(authProvider, modelRegistry, preferCustomEndpoint);
      const fallback = providerDefault ?? getDefaultSummarizationModel();
      debug(`[queryLlm] Model ${bareModel} incompatible with ${authProvider} (resolved: ${resolvedProvider}), falling back to ${fallback}`);
      model = fallback;
    }
  }

  const runQueryWithModel = async (modelId: string): Promise<string> => {
    debug(`[queryLlm] Using model: ${modelId}`);
    const piModel = resolvePiModel(
      modelRegistry,
      modelId,
      config.piAuth?.provider,
      preferCustomEndpoint,
    );
    if (!piModel) {
      throw new Error(
        `Could not resolve mini model "${modelId}" for provider "${config.piAuth?.provider ?? '(unknown)'}"`,
      );
    }

    const settingsManager = SettingsManager.inMemory();
    const ephemeralOptions: CreateAgentSessionOptions = {
      cwd: context.cwd,
      authStorage,
      modelRegistry,
      tools: [],
      sessionManager: PiSessionManager.inMemory(),
      settingsManager,
      model: piModel,
      ...(piThinkingLevel ? { thinkingLevel: piThinkingLevel } : {}),
    };
    const promptOverride = createSystemPromptOverride();
    promptOverride.set(request.systemPrompt ?? 'Reply with ONLY the requested text. No explanation.');
    const resourceLoader = new DefaultResourceLoader({
      cwd: context.cwd,
      agentDir: config.agentDir || getAgentDir(),
      settingsManager,
      extensionFactories: [
        promptOverride.extension,
        createProviderHooks({ enable1MContext: config.enable1MContext === true }),
      ],
      noExtensions: true,
      noSkills: true,
      noPromptTemplates: true,
      noThemes: true,
      noContextFiles: true,
      systemPromptOverride: promptOverride.overrideResourcePrompt,
    });
    await resourceLoader.reload();
    ephemeralOptions.resourceLoader = resourceLoader;

    const { session } = await createAgentSession(ephemeralOptions);
    try {
      try {
        await session.setModel(piModel);
      } catch {
        debug('[queryLlm] Failed to set model on ephemeral session, proceeding with default');
      }

      debug(`[queryLlm] Created ephemeral session: ${session.sessionId}`);
      let result = '';
      let lastError = '';
      const unsubscribe = session.subscribe((event: AgentSessionEvent) => {
        if (event.type !== 'message_end') return;
        const message = event.message as {
          role?: string;
          content?: string | Array<{ type: string; text?: string }>;
          stopReason?: string;
          errorMessage?: string;
        };
        if (message.role !== 'assistant') return;
        if (message.stopReason === 'error' && message.errorMessage) {
          lastError = message.errorMessage;
          debug(`[queryLlm] API error in message_end: ${message.errorMessage}`);
        }
        if (typeof message.content === 'string') {
          result = message.content;
        } else if (Array.isArray(message.content)) {
          result = message.content
            .filter(content => content.type === 'text' && content.text)
            .map(content => content.text!)
            .join('');
        }
      });

      try {
        await withTimeout(
          session.prompt(request.prompt),
          LLM_QUERY_TIMEOUT_MS,
          `queryLlm timed out after ${LLM_QUERY_TIMEOUT_MS / 1000}s`,
        );
        debug(`[queryLlm] Result length: ${result.trim().length}`);
        if (!result.trim() && lastError) throw new Error(lastError);
        return result.trim();
      } finally {
        unsubscribe();
      }
    } finally {
      session.dispose();
    }
  };

  const fallbackCandidates = [
    'pi/gpt-5-mini',
    config.miniModel,
    getDefaultSummarizationModel(),
  ].filter((candidate): candidate is string => (
    !!candidate && !isDeniedMiniModelId(candidate, piAuthProvider)
  ));

  const triedModels = new Set<string>();
  let currentModel = model;
  while (true) {
    triedModels.add(currentModel);
    try {
      const text = await runQueryWithModel(currentModel);
      return { text, model: currentModel };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (!isModelNotFoundError(message)) throw error;

      const retryModel = fallbackCandidates.find(candidate => {
        if (triedModels.has(candidate)) return false;
        const resolved = resolvePiModel(
          modelRegistry,
          candidate,
          config.piAuth?.provider,
          preferCustomEndpoint,
        );
        if (!resolved) return false;
        const provider = (resolved as { provider?: string }).provider;
        return !config.piAuth
          || provider === config.piAuth.provider
          || provider === 'custom-endpoint';
      });
      if (!retryModel) throw error;

      debug(`[queryLlm] Model ${currentModel} not found, retrying with ${retryModel}`);
      currentModel = retryModel;
    }
  }
}
