// input: Fake Pi sessions, Storyflow prompts, and representative global Skill metadata
// output: Regression assertions for stable prompt overrides and progressive Skill disclosure
// pos: Contract test for the Storyflow-to-Pi system prompt bridge

import { describe, expect, it } from 'bun:test';
import {
  createSyntheticSourceInfo,
  type AgentSession,
  type Skill,
} from '@earendil-works/pi-coding-agent';
import { applySystemPromptOverride } from './system-prompt-override.ts';

/**
 * Regression contract for craft-agents-oss#648.
 *
 * Pi SDK's `session.prompt()` resets `agent.state.systemPrompt` to
 * `_baseSystemPrompt` on every turn (agent-session.js ~L796), and
 * `_baseSystemPrompt` itself can be regenerated by the SDK via
 * `_rebuildSystemPrompt()` when tools change. To survive both paths we must
 * stamp ALL THREE internals on the session — dropping any one of them
 * re-introduces the original bug:
 *   - `agent.state.systemPrompt` — what the next agent_loop turn ships to the LLM
 *   - `_baseSystemPrompt` — what the SDK falls back to when no extension override
 *   - `_rebuildSystemPrompt` — what the SDK calls on tool/resource rebuilds
 *
 * Pattern matches OpenClaw's `applySystemPromptOverrideToSession`.
 */

type StampedSession = {
  agent: { state: { systemPrompt?: string } };
  _baseSystemPrompt?: string;
  _rebuildSystemPrompt?: (toolNames: string[]) => string;
};

function makeFakeSession(): StampedSession {
  return {
    agent: { state: {} },
  };
}

describe('applySystemPromptOverride', () => {
  it('stamps state.systemPrompt', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'CRAFT_PROMPT');
    expect(session.agent.state.systemPrompt).toBe('CRAFT_PROMPT');
  });

  it('stamps the private _baseSystemPrompt field so session.prompt() reset survives', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'CRAFT_PROMPT');
    expect(session._baseSystemPrompt).toBe('CRAFT_PROMPT');
  });

  it('replaces _rebuildSystemPrompt with a constant function so tool-change rebuilds survive', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'CRAFT_PROMPT');
    expect(typeof session._rebuildSystemPrompt).toBe('function');
    // Must return our prompt regardless of which tool names the SDK passes in.
    expect(session._rebuildSystemPrompt!(['read', 'bash'])).toBe('CRAFT_PROMPT');
    expect(session._rebuildSystemPrompt!([])).toBe('CRAFT_PROMPT');
  });

  it('overwrites previously stamped values on a re-application', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'FIRST');
    applySystemPromptOverride(session as unknown as AgentSession, 'SECOND');
    expect(session.agent.state.systemPrompt).toBe('SECOND');
    expect(session._baseSystemPrompt).toBe('SECOND');
    expect(session._rebuildSystemPrompt!([])).toBe('SECOND');
  });

  it('preserves Pi global Skill metadata for automatic invocation', () => {
    const session = makeFakeSession();
    const skill: Skill = {
      name: 'outline-architecture',
      description: 'Design a story outline.',
      filePath: '/home/user/.craft-agent/skills/outline-architecture/SKILL.md',
      baseDir: '/home/user/.craft-agent/skills/outline-architecture',
      sourceInfo: createSyntheticSourceInfo(
        '/home/user/.craft-agent/skills/outline-architecture/SKILL.md',
        { source: 'storyflow-project', scope: 'project' },
      ),
      disableModelInvocation: false,
    };

    applySystemPromptOverride(session as unknown as AgentSession, 'CRAFT_PROMPT', [skill]);

    expect(session.agent.state.systemPrompt).toContain('CRAFT_PROMPT');
    expect(session.agent.state.systemPrompt).toContain('<available_skills>');
    expect(session.agent.state.systemPrompt).toContain('<name>outline-architecture</name>');
    expect(session._rebuildSystemPrompt!([])).toBe(session.agent.state.systemPrompt);
  });
});
